name: TESTE RUNNER LOCAL

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Mostrar máquina
        run: hostname

      - name: Teste simples
        run: echo "Runner local funcionando 🚀"
